### ISSUE TITLE
Public Tests [Feature Request]

### ISSUE THREAD

**Issue by xuri-ajiva** [AuD-2022/AuD-2022-H05-Student#2]
Hallo allerseits,
Wann kann den mit den Public Tests gerechnet werden?

LG

**Comment by Rdeisenroth** [comment]
Die Public-Tests sind jetzt verfügbar. Hier [der entsprechende Commit](https://github.com/AuD-2022/AuD-2022-H05-Student/commit/10ee87a00f0569474c5fb60e98569a8c7a86a351).
